name: TimerBan
author: onebone
api: 3.0.0-ALPHA7
version: "2.1-r110patched"
main: onebone\timerban\TimerBan
commands:
 timerban:
  usage: /timerban <add|remove|list> <player> <time> [reason...]
  permission: timerban.command.timerban;timerban.command.timerban.add;timerban.command.timerban.pardon;timerban.command.timerban.list
 timerbanip:
  usage: /timerbanip <add|remove|list> <player|IP> <time> [reason...]
  permission: timerban.command.timerbanip;timerban.command.timerbanip.add;timerban.command.timerbanip.pardon;timerban.command.timerbanip.list
permissions:
 timerban.*:
  description: Allows all permission of TimerBan
  children:
   timerban.command.*:
    description: Allows all commands of TimerBan
    children:
     timerban.command.timerban:
      description: Allows ban command
     timerban.command.timerbanip:
      description: Allows IP ban command